#!/usr/bin/env node
/*
  NOTE: THIS SCRIPT WAS "VIBE CODED"
  meaning it was entirely generated by AI (Claude Sonnet 4.6)
  so far it's been working great (but be warned)
*/
/**
 * Word count script for netnet.studio educational content.
 * Counts words in netitor edu-data JSON files, linter friendly error messages,
 * tutorial widget text, demo step explanations, and conversation dialogue.
 *
 * Usage: node my_modules/word-count.js [--verbose]
 */

const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const VERBOSE = process.argv.includes('--verbose')

// ─── helpers ────────────────────────────────────────────────────────────────

function stripHTML (str) {
  return str.replace(/<[^>]+>/g, ' ').replace(/&[a-z]+;/g, ' ').replace(/\s+/g, ' ').trim()
}

function countWords (str) {
  if (!str || !str.trim()) return 0
  return str.trim().split(/\s+/).length
}

// ─── JSON edu-data extractors ────────────────────────────────────────────────

function extractDescriptionText (data) {
  let words = 0
  for (const key of Object.keys(data)) {
    const entry = data[key]
    if (entry && entry.description && entry.description.text) {
      words += countWords(entry.description.text)
    }
  }
  return words
}

function extractTopLevelText (data) {
  let words = 0
  for (const key of Object.keys(data)) {
    const entry = data[key]
    if (entry && entry.text) {
      words += countWords(entry.text)
    }
  }
  return words
}

function extractNestedDescriptionText (data) {
  let words = 0
  for (const group of Object.keys(data)) {
    const entries = data[group]
    if (entries && typeof entries === 'object') {
      words += extractDescriptionText(entries)
    }
  }
  return words
}

// ─── JS linter extractor ────────────────────────────────────────────────────

function extractFriendlyFromJS (filepath) {
  const src = fs.readFileSync(filepath, 'utf8')
  let total = 0
  let m

  const templateRe = /obj\.friendly\s*=\s*`([\s\S]*?)`/g
  while ((m = templateRe.exec(src)) !== null) {
    const text = stripHTML(m[1])
    total += countWords(text)
    if (VERBOSE) console.log(`  [template] ${text.substring(0, 80)}...`)
  }

  const stringRe = /obj\.friendly\s*=\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)")/g
  while ((m = stringRe.exec(src)) !== null) {
    const raw = m[1] !== undefined ? m[1] : m[2]
    const text = stripHTML(raw)
    total += countWords(text)
    if (VERBOSE) console.log(`  [string] ${text.substring(0, 80)}...`)
  }

  return total
}

// ─── content extractor ──────────────────────────────────────────────────────

function extractContentFromJS (filepath) {
  const src = fs.readFileSync(filepath, 'utf8')
  let total = 0
  let m

  const templateRe = /content\s*:\s*`([\s\S]*?)`/g
  while ((m = templateRe.exec(src)) !== null) {
    const text = stripHTML(m[1])
    total += countWords(text)
    if (VERBOSE) console.log(`  [template] ${text.substring(0, 80)}...`)
  }

  const stringRe = /content\s*:\s*(?:'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)")/g
  while ((m = stringRe.exec(src)) !== null) {
    const raw = m[1] !== undefined ? m[1] : m[2]
    const text = stripHTML(raw)
    total += countWords(text)
    if (VERBOSE) console.log(`  [string] ${text.substring(0, 80)}...`)
  }

  return total
}

// ─── demo extractor ─────────────────────────────────────────────────────────

function extractDemoInfoText (data) {
  let words = 0
  if (Array.isArray(data.info)) {
    for (const step of data.info) {
      if (step && step.text) {
        words += countWords(stripHTML(step.text))
      }
    }
  }
  return words
}

// ─── run ─────────────────────────────────────────────────────────────────────

const results = []
let grandTotal = 0

function addResult (label, words) {
  results.push({ label, words })
  grandTotal += words
  if (VERBOSE) console.log()
}

// ── netitor edu-data ──────────────────────────────────────────────────────────

const eduBase = path.join(ROOT, 'www/core/netitor/src/edu-data')
const linterBase = path.join(ROOT, 'www/core/netitor/src/linters')

const cssFiles = [
  { file: 'css/at-rules.json', fn: extractDescriptionText },
  { file: 'css/data-types.json', fn: extractDescriptionText },
  { file: 'css/display.json', fn: extractDescriptionText },
  { file: 'css/functions.json', fn: extractTopLevelText },
  { file: 'css/properties.json', fn: extractDescriptionText },
  { file: 'css/pseudo-classes.json', fn: extractDescriptionText },
  { file: 'css/pseudo-elements.json', fn: extractDescriptionText },
  { file: 'css/units.json', fn: extractTopLevelText }
  // css/colors.json intentionally skipped — no description text
]

for (const { file, fn } of cssFiles) {
  if (VERBOSE) console.log(`\n── ${file}`)
  const data = require(path.join(eduBase, file))
  addResult(file, fn(data))
}

const htmlFiles = [
  { file: 'html/elements.json', fn: extractDescriptionText },
  { file: 'html/attributes.json', fn: extractDescriptionText },
  { file: 'html/svg-elements.json', fn: extractDescriptionText },
  { file: 'html/svg-attributes.json', fn: extractDescriptionText }
]

for (const { file, fn } of htmlFiles) {
  if (VERBOSE) console.log(`\n── ${file}`)
  const data = require(path.join(eduBase, file))
  addResult(file, fn(data))
}

const jsFlatFiles = [
  'js/arrays.json', 'js/canvas2d.json', 'js/date.json',
  'js/document.json', 'js/dom-canvas.json', 'js/dom-element.json',
  'js/dom-event-target.json', 'js/dom-media.json', 'js/dom-node.json',
  'js/history.json', 'js/html-element.json', 'js/location.json',
  'js/math.json', 'js/navigator.json', 'js/number.json',
  'js/refs.json', 'js/string.json', 'js/syntax.json', 'js/window.json'
]

for (const file of jsFlatFiles) {
  if (VERBOSE) console.log(`\n── ${file}`)
  const data = require(path.join(eduBase, file))
  addResult(file, extractDescriptionText(data))
}

const jsNestedFiles = ['js/events.json']
for (const file of jsNestedFiles) {
  if (VERBOSE) console.log(`\n── ${file}`)
  const data = require(path.join(eduBase, file))
  addResult(file, extractNestedDescriptionText(data))
}

const customFile = 'custom/nn-netitor-docs.json'
if (VERBOSE) console.log(`\n── ${customFile}`)
const customData = require(path.join(eduBase, customFile))
addResult(customFile, extractNestedDescriptionText(customData))

const linterFiles = [
  'css-friendly-translator.js',
  'html-friendly-translator.js',
  'js-friendly-translator.js'
]

for (const file of linterFiles) {
  if (VERBOSE) console.log(`\n── linters/${file}`)
  addResult(`linters/${file}`, extractFriendlyFromJS(path.join(linterBase, file)))
}

// ── widget convos ─────────────────────────────────────────────────────────────

const widgetsBase = path.join(ROOT, 'www/widgets')
for (const widget of fs.readdirSync(widgetsBase).sort()) {
  if (widget === 'EXAMPLE-WIDGET' || widget === 'index.js') continue
  const p = path.join(widgetsBase, widget, 'convo.js')
  if (!fs.existsSync(p)) continue
  if (VERBOSE) console.log(`\n── widgets/${widget}/convo.js`)
  addResult(`convos/widgets/${widget}`, extractContentFromJS(p))
}

if (VERBOSE) console.log('\n── core/utils-convo.js')
addResult('convos/core/utils-convo', extractContentFromJS(path.join(ROOT, 'www/core/utils-convo.js')))

// ── demo info text ────────────────────────────────────────────────────────────

const demoBase = path.join(ROOT, 'data/demos')
for (const file of fs.readdirSync(demoBase).filter(f => f.endsWith('.json')).sort()) {
  if (VERBOSE) console.log(`\n── demos/${file}`)
  const data = JSON.parse(fs.readFileSync(path.join(demoBase, file), 'utf8'))
  addResult(`demos/${file}`, extractDemoInfoText(data))
}

// ── template convos ───────────────────────────────────────────────────────────

const templateBase = path.join(ROOT, 'data/templates')
for (const dir of fs.readdirSync(templateBase).sort()) {
  const p = path.join(templateBase, dir, 'convo.js')
  if (!fs.existsSync(p)) continue
  if (VERBOSE) console.log(`\n── templates/${dir}/convo.js`)
  addResult(`convos/templates/${dir}`, extractContentFromJS(p))
}

// ─── output ──────────────────────────────────────────────────────────────────

const colW = 46
console.log('\n' + '─'.repeat(colW + 10))
console.log('netnet.studio educational content word count')
console.log('─'.repeat(colW + 10))

const grouped = [
  { heading: 'CSS edu-data', prefix: 'css/' },
  { heading: 'HTML edu-data', prefix: 'html/' },
  { heading: 'JS edu-data', prefix: 'js/' },
  { heading: 'Custom docs', prefix: 'custom/' },
  { heading: 'Friendly error messages', prefix: 'linters/' },
  { heading: 'Widget conversations', prefix: 'convos/widgets/' },
  { heading: 'Core conversations', prefix: 'convos/core/' },
  { heading: 'Demo step explanations', prefix: 'demos/' },
  { heading: 'Template conversations', prefix: 'convos/templates/' }
]

for (const { heading, prefix } of grouped) {
  const rows = results.filter(r => r.label.startsWith(prefix))
  if (!rows.length) continue
  const subtotal = rows.reduce((s, r) => s + r.words, 0)
  console.log(`\n  ${heading}`)
  for (const r of rows) {
    const label = r.label.padEnd(colW)
    console.log(`    ${label} ${r.words.toLocaleString()}`)
  }
  console.log(`    ${'subtotal'.padEnd(colW)} ${subtotal.toLocaleString()}`)
}

console.log('\n' + '─'.repeat(colW + 10))
console.log(`  ${'GRAND TOTAL'.padEnd(colW)} ${grandTotal.toLocaleString()}`)
console.log('─'.repeat(colW + 10) + '\n')
